### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by superkartoffel** [Unity3D-Wine-Support/Unity3D-on-Wine#44]
Has anyone tried building for android in unity using wine? I ran into several issues because my linux-jdk was not properly recognized by unity (aapt.exe was in the wrong folder for example) and windows-jdk could not be installed using wine (installer segfaults).

I just wanted to ask if anyone has even tried to build for android in wine, because I couldn't find any information.

**Comment by DoctorJellyface** [comment]
Nope, sorry, but I think someone got it working. Not sure who or where, but you might want to check the issues here and the forum thread.

**Comment by Abscissa** [comment]
It's a little bit tricky, but I've done it. My brain's falling asleep for the night at the moment, but I'll dig up my notes on it tomorrow.

**Comment by DoctorJellyface** [comment]
Nice, thanks.

**Comment by Abscissa** [comment]
Note that I haven't attempted any of this with 64-bit versions yet since Unity3D didn't support 64-bit until very recently (and I haven't actually needed 64-bit Unity3D just yet). So all this uses 32-bit versions of Java SDK/Android SDK/Unity3D which has worked for me.

One of the keys here is that (in my experience) just for this initial setup, you do **temporarily** need access to Windows, either in a VM (such as VMware Player) or any normal installation. But then, after setup you won't need Windows anymore, at least until you want to update the Android SDK.

Steps To Setup Unity3D Under Wine to Build For Android:

- Make sure your copy of wine is reasonably up-to-date (I've had trouble installing JDK7 under wine in the past, not sure if it was fixed in a wine update or a JDK7 update, but it works for me with wine 1.6.2 and the version of JDK mentioned below. So try to update wine if you can.)

- Download the latest version of [Java SDK7 for Win32](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html). I've never  been able to get JDK8 to install under wine, but the latest version of JDK7 works for me: 7u76 (Note you have to scroll down to get to the 7u76 section. They confusingly stick the 7u75 stuff at the top of the page.)

- If you installed Unity3D through PlayOnLinux and the "unity.pol" script (That's how I did it), then install JDK7 like this: Run PlayOnLinux, Go to "Unity3D" -> "Configure" -> "Miscellaneous" Tab -> "Run a .exe file in this virtual drive" -> Select the JDK 7 Win32 installer. And then just follow the installation prompts.

- If you didn't use PlayOnLinux to install Unity3D, then you should be able to just install JDK7 like: ```wine jdk-7u76-windows-i586.exe```.

- Download [Android SDK for Win32](https://developer.android.com/sdk/index.html). I didn't bother with Android Studio. Just scroll down that page to the "SDK Tools Only" section and grab the ZIP, no need to bother with the installer.

- Extract the Android SDK for Windows zip file.

- Here's the part you have to do on a real Windows machine (A Windows VM will also work fine, I recommend the free VMware Player. Or you can just find someone who'll let you use their Windows box for a few minutes. But this part doesn't seem to work under wine for me.): In Windows, go to the extracted Android SDK files, and run ```SDK Manager.exe```. Use that tool to install/update whatever Android SDK components you need. It's pretty simple to use.

- Copy the Android SDK directory back over to your Linux box, wherever you want it installed.

- If you're using a slightly older version of Unity3D, you may need to go into the Android SDK directory and copy ```sdk/build-tools/[any of these directories]/zipalign.exe``` into ```sdk/tools/```. If you get errors about "zipalign" when you try to build, then you know you need to do this ;)

- Final step: In Unity3D, go to "Edit" -> "Preferences" -> "External Tools", and set "Android SDK Location" to the "sdk" subdirectory inside wherever you placed your Android SDK directory.

**Comment by superkartoffel** [comment]
Hi  Abscissa,

I finally found the time to try out your how-to. And it totally works :)
Thank you very much!
